### ISSUE TITLE
living dead press a to continue

### ISSUE THREAD

**Issue by MrBlinky** [Press-Play-On-Tape/PrinceOfArabia#108]
1.0028 l4  when having your sword drawn and you move back from the chopper in this room you'll (partially) die and the press a to continue bar shows. Pressing A won't work and the only option is to go back to the main menu if you didn't save.
![poa-nochopper](https://user-images.githubusercontent.com/4971163/224478522-4ba6702b-0b1e-4018-a059-2ad4d1ee3735.gif)

**Comment by filmote** [comment]
OK .. I have done some more on this.

**Comment by MrBlinky** [comment]
Seems that did it. No more afterlife fun.
