### ISSUE TITLE
In-game menu missing cursor

### ISSUE THREAD

**Issue by ace-dent** [Press-Play-On-Tape/PrinceOfArabia#118]
Tested with v1.0030, FX Hardware.
- With a Saved game, prince dies.
- From the 'Press A to Continue' screen, bring up the in game menu.
- Select `Clear` but then dismiss with `No`.
- Menu cursor (dagger?) has temporarily disappeared.

**Comment by filmote** [comment]
'It's not great because the user is left wondering if it just cleared or not?... so I had to go back into the menu to see if my save was still there.'

I agree.

I have restored the return t the previous screen.

**Comment by MrBlinky** [comment]
I'm not happy with the return to menu after choosing any of the confirm options. it introduces a new bug keeping the green LED on while you stay in the menu. having the cursor jump to resume also feels odd.

I think after choosing any of the confirm options the menu should close. There is already the LED confirming the clear. How many confirmations does one need?

**Comment by filmote** [comment]
I have reverted back to the close menu automatically option.

**Comment by ace-dent** [comment]
Confirmed, FIXED, with v1.01 Beta 004 on Arduboy FX hardware.
- The cursor is always shown, and menu navigation works as expected. Thanks.

**Comment by filmote** [comment]
Thanks , I will close it.
