### ISSUE TITLE
255 Saves is too limiting...

### ISSUE THREAD

**Issue by ace-dent** [Press-Play-On-Tape/PrinceOfArabia#119]
I think we need to change `playSave` and `highSaves` etc. from 8 --> 16bit unsigned.
I could probably blow through the ~20 saves per level allowance (255/13).
Important to do before release, so the game saves aren't made invalid.

_Alternatively_ we can add some code to stop it overflowing with the increment (so max out at 255).
https://github.com/filmote/PrinceOfArabia/blob/8bc0b63c24e8ad10cdebeb2ddfb1ecd02d6e531b/PrinceOfArabia_Game.ino#L1231

**Comment by filmote** [comment]
Fixed in prod release.
