### ISSUE TITLE
new game doesn't reset health bars

### ISSUE THREAD

**Issue by MrBlinky** [Press-Play-On-Tape/PrinceOfArabia#125]
Version 1.1 Beta 002 
If you saved a game with more then 3 health bars then when you start a new game your health will be equal to those of the saved game.

**Comment by MrBlinky** [comment]
initial report is wrong. also get 4 bars after erasing save game and a reset. It seems you always get 4 healthbars now?

**Comment by filmote** [comment]
I am not seeing that.

I tested it by adding a few health elements to Level 1. Should this have reproduced the issue?


![aaa](https://user-images.githubusercontent.com/17228490/226163134-e3b001b2-cbf7-4899-906a-bd7f6d0cfbb6.gif)

**Comment by MrBlinky** [comment]
I just noticed at one point that I had 4 health bars when I started a new game. With the new beta I can't reproduce it.
