### ISSUE TITLE
Green LED remains on after erasing game

### ISSUE THREAD

**Issue by MrBlinky** [Press-Play-On-Tape/PrinceOfArabia#126]
Version 1.1 Beta 002 title says it all

**Comment by MrBlinky** [comment]
I tested Version 1.1 Beta 002 rebuild from source with USE LED enabled.

**Comment by MrBlinky** [comment]
added detail: The green LED remains on until you leave the menu

**Comment by filmote** [comment]
Fixed.  Will be incorporated in Beta 004.

**Comment by ace-dent** [comment]
Confirmed, FIXED, with v1.01 Beta 004 on Arduboy FX hardware.

**Comment by filmote** [comment]
Thanks for confirming.
