### ISSUE TITLE
Jumping through walls

### ISSUE THREAD

**Issue by ace-dent** [Press-Play-On-Tape/PrinceOfArabia#131]
Tested with v1.01 Beta 004, Simulator.
On Level 2, it is possible (with a precisely timed jump) to pass through the wall.

![fall](https://user-images.githubusercontent.com/473224/226779628-34c0ef58-c78f-4af1-87da-6a9339e3bdf1.gif)

**Comment by filmote** [comment]
Ah nice, [petrov dmitriy](https://community.arduboy.com/u/dmtry78) was telling us about it.

**Comment by ace-dent** [comment]
Easier example to recreate from L2. 
Just jump from start position of the final ledge.

![fall2](https://user-images.githubusercontent.com/473224/226786321-e647a02c-67cb-4372-8db8-d4b48521f748.gif)

**Comment by filmote** [comment]
Updated in Beta 005

**Comment by ace-dent** [comment]
Tested with Version 1.01 Beta 012, Sim.
-- Cannot recreate the bug; Fixed! Please Close.
