### ISSUE TITLE
longjump left issue

### ISSUE THREAD

**Issue by MrBlinky** [Press-Play-On-Tape/PrinceOfArabia#135]
V1.01 Beta 007 level one in room with sword. the long jump often doesn't register when running. it only does from standing position.

![recording_20230325123637](https://user-images.githubusercontent.com/4971163/227712270-3402a293-4a8e-4360-822a-e3b9e180fa24.gif)

**Comment by filmote** [comment]
I have updated this in Beta 008.

**Comment by ace-dent** [comment]
Tested with Version 1.01 Beta 012, FX Hardware.
-- Tried to re-create but seems Fixed. In general jumping 'feels' better. Please Close.
