### ISSUE TITLE
Chopper trap noise (2)

### ISSUE THREAD

**Issue by ace-dent** [Press-Play-On-Tape/PrinceOfArabia#137]
Regression of #90.
Tested with v1.01 Beta 008, FX hardware. Level 7.

- With new walking sounds added, if you pass through chopper at a certain point in walk (/sound) cycle, the death tune won't play.

https://user-images.githubusercontent.com/473224/227780923-32cf9897-02fb-4b42-afed-9059a1c76179.mp4

**Comment by filmote** [comment]
Might have to ask Mr.Blinky to help with this .. it should work.

**Comment by filmote** [comment]
Fixed (?) in Beta 009.

**Comment by ace-dent** [comment]
Tested with Version 1.01 Beta 012, FX Hardware.
-- This was a hard bug to reproduce (originally). Retested in same spot and seems fixed. Please Close.
