### ISSUE TITLE
Chopper trap sound when not visible

### ISSUE THREAD

**Issue by ace-dent** [Press-Play-On-Tape/PrinceOfArabia#138]
Tested with v1.01 Beta 008, real FX hardware.

- Should chopper trap sounds be played when it is off screen?
- E.g. L7- trap is on next level up, but sounds play on the lower level... 

https://user-images.githubusercontent.com/473224/227781204-d1057e8a-8a28-4422-a877-af8cefc5c2b0.mp4

**Comment by filmote** [comment]
Probably not.  I will have a look at that.

**Comment by filmote** [comment]
Fixed (?) in Beta 009.

**Comment by ace-dent** [comment]
Tested with Version 1.01 Beta 012, FX Hardware.
-- Fixed! Thanks. Please Close.
