### ISSUE TITLE
Sword fight with chopper trap

### ISSUE THREAD

**Issue by ace-dent** [Press-Play-On-Tape/PrinceOfArabia#141]
Tested with v1.01 Beta 008, Sim.

- L8 requires a sword fight across a chopper trap.
- If your sword touches the trap, you die. This seems impossible!

![Sword trap](https://user-images.githubusercontent.com/473224/227814502-160e4037-6d4b-4580-9cc5-9777ead8af13.gif)

**Comment by ace-dent** [comment]
Seems in other versions the guard hangs back until you have traversed the trap:
https://youtu.be/IFoQyvJ3JnI?t=184

**Comment by filmote** [comment]
That's a good fix.  I will prevent right-ward movements so you can get through easier.

**Comment by filmote** [comment]
Moved him to the left. Fixed (?) in Beta 009.

**Comment by ace-dent** [comment]
Tested with Version 1.01 Beta 012, FX Hardware.
-- Looks good; Guard now further left and feels fair. Fixed, please Close.
