### ISSUE TITLE
Long jump with tile switch/ gate

### ISSUE THREAD

**Issue by ace-dent** [Press-Play-On-Tape/PrinceOfArabia#142]
Tested with v1.01, Beta 008. Sim.

- L8 taking a long jump while a gate is opening - is not possible (prince just drops).
- Need to wait until the gate is fully open to make the jump.

![LongJump](https://user-images.githubusercontent.com/473224/227814785-8c9752a6-4c29-4361-bddb-0cda1029db92.gif)

**Comment by filmote** [comment]
Fixed (?) in Beta 009.

**Comment by ace-dent** [comment]
Tested with Version 1.01 Beta 012, FX Hardware.
-- Seems fixed/ or perhaps gate just opens quicker? Please Close.
