### ISSUE TITLE
Falling tile can be climbed through

### ISSUE THREAD

**Issue by ace-dent** [Press-Play-On-Tape/PrinceOfArabia#147]
Tested with Version 1.01 Beta 012, Sim.
- L2: See recording.
- When stood right on the edge it's possible to climb down through the platform, without triggering the broken tile to fall.

![SolidAsArock](https://user-images.githubusercontent.com/473224/229215559-259580ea-e63d-4e6d-ae12-5898a6a968e2.gif)

**Comment by filmote** [comment]
Fixed in Version 1.01 Beta 013.

**Comment by filmote** [comment]
Bad:

![Image](https://user-images.githubusercontent.com/17228490/229263054-21abf4c4-dc92-4507-88df-f72cc14c5531.gif)

Good:

![Image](https://user-images.githubusercontent.com/17228490/229263062-9b9dca1c-6d44-4f86-a260-85ab0045c4b7.gif)

**Comment by ace-dent** [comment]
Tested with Version 1.01 Beta 013, Sim.
- Player can no longer climb down until the tile has fallen.
- This fixes the issue, but the previous behaviour - climbing down would cause the tile to immediately fall- is preferable for unbroken game play.

**Comment by filmote** [comment]
In the original game, bunny-hopping to the edge would not make the tile drop - you needed to bunny hop right onto the tile for this to happen.  This solution is more than acceptable so I am going to close this one.
