### ISSUE TITLE
L9 Ledge fall trap

### ISSUE THREAD

**Issue by ace-dent** [Press-Play-On-Tape/PrinceOfArabia#151]
Tested with Version 1.01 Beta 012, Sim
- Is the L9 ledge fall trap deliberate? 
- Even slow steps lead to death. (Crouching hops are ok).
- My feeling is that this difficulty is acceptable if we are using Save... just wanted to check it's be design.

![LedgeTrap](https://user-images.githubusercontent.com/473224/229248084-16a4e23e-cb0a-42d3-91ac-fd06ba9fb429.gif)

**Comment by filmote** [comment]
Its how it is in the original:



![Image](https://user-images.githubusercontent.com/17228490/229259000-7dd20e55-a45c-47bf-9dd5-2f4fb0523603.png)


That's not to say we have to keep it that way.

https://www.popuw.com/images/maps/adomatic/level9_mac.png

**Comment by ace-dent** [comment]
That makes sense. No issue. Please Close.
