### ISSUE TITLE
Prince skid animation has odd frames

### ISSUE THREAD

**Issue by ace-dent** [Press-Play-On-Tape/PrinceOfArabia#152]
Tested with Version 1.01 Beta 012, Sim.
- Running right to left, quickly change direction so the prince skids.
- There are a few odd frames where the sprite is facing the wrong way.
- I've added a red marker to the recording.
- This may also happen L>R skidding, but doesn't seem as noticeable.

![OddFrame](https://user-images.githubusercontent.com/473224/229249283-e078dc25-0b3a-4d20-9506-8ce12a871e67.gif)

**Comment by filmote** [comment]
Looks a little better:

![Image](https://user-images.githubusercontent.com/17228490/229263099-046dfcb5-fc7d-44dd-a818-9cc7f5302179.gif)

Fixed in Version 1.01 Beta 013.

**Comment by ace-dent** [comment]
Tested with Version 1.01 Beta 013, Sim.
--  Fixed! Thanks. Please Close.
