### ISSUE TITLE
L8 inbetween chopper kill

### ISSUE THREAD

**Issue by MrBlinky** [Press-Play-On-Tape/PrinceOfArabia#155]
v101beta013 you get killed walking midway between the blade

![recording_20230401143248](https://user-images.githubusercontent.com/4971163/229286376-c080f160-6db8-4b35-bd11-3e207cc47654.gif)

**Comment by filmote** [comment]
Too easy.



![Image](https://user-images.githubusercontent.com/17228490/229333679-c5ae322d-f1b8-40ea-95ac-817eff70fad9.gif)



![Image](https://user-images.githubusercontent.com/17228490/229333685-c1c105aa-b6ac-4d61-ba4b-dc7e5ddeb1a5.gif)

Fixed in Version 1.01 Beta 013.

**Comment by MrBlinky** [comment]
confirmed in 1.01 beta 18
