### ISSUE TITLE
L8 through the wall

### ISSUE THREAD

**Issue by MrBlinky** [Press-Play-On-Tape/PrinceOfArabia#156]
v101beta13 in L8 it's possible to go through the wall again

![recording_20230401155323](https://user-images.githubusercontent.com/4971163/229290418-c3d34c23-c285-4fd4-bf46-a729012147b1.gif)

**Comment by filmote** [comment]
The video below shows me jumping from positions 2, 6 and 10 and they all seem to work properly.  In your video though it looks like you are turning or something at the end that I cannot make out.  How did you do it?



![Image](https://user-images.githubusercontent.com/17228490/229330377-0a0822f4-e913-4d89-b67e-821ed470c1bc.gif)

**Comment by MrBlinky** [comment]
Silly me forgetting to write the how. 1st time I was running and jumping into the room. I couldn't recreate that situation as i didn't keep track of it. 

In the recreation I go in the room to the left facing left. from a standing position I inmediately turn right, run and jump simultaniously and dont release the right and jump buttons.

**Comment by filmote** [comment]
Fixed in Beta 015 (maybe).

**Comment by MrBlinky** [comment]
yep can't get through the wall again (here).

**Comment by filmote** [comment]
Are you saying you can't get through the wall (which is good) or you can again (bad)?

**Comment by filmote** [comment]
Ignore the above .. I see you closed it so must be good!
