### ISSUE TITLE
ingame menu appears when shuffle walking into a wall

### ISSUE THREAD

**Issue by MrBlinky** [Press-Play-On-Tape/PrinceOfArabia#159]
beta0014 With B button as part of the shuffle  walk, the ingame menu appears when you crash into a wall.

maybe trigger the shuffle walk after left/right has pressed? also has the advantage that you can go instandly from running to shuffle walking

![recording_20230402124344](https://user-images.githubusercontent.com/4971163/229345499-28cb2e52-cbfa-4492-88f8-db2e51b6c51f.gif)

**Comment by filmote** [comment]
Beta 015 maybe fixed (!)

**Comment by MrBlinky** [comment]
didn't test this until 1.01 beta 18. The menu doesn't pop up anymore when shuffling into a wall.
