### ISSUE TITLE
another run through the wall

### ISSUE THREAD

**Issue by MrBlinky** [Press-Play-On-Tape/PrinceOfArabia#164]
I once managed to go through the wall again. Took a while to recreate it but I found it :

In level one after getting the sword, climb up the platform to the right and bluntly run to the right into the wall.
Now turn around and jump out to the left room, walk a few tiles, turn around and run into the wall again.... No clifhanger ;)

![recording_20230422190612](https://user-images.githubusercontent.com/4971163/233795048-8dbc1369-7372-40a7-88e6-0e764d63c96f.gif)

**Comment by MrBlinky** [comment]
Starting to master this move. It's also possible to do this  in the starting room:

![recording_20230422191649](https://user-images.githubusercontent.com/4971163/233795460-2d7ca68d-dcde-4098-a8ab-ec1a8cc48ab8.gif)

**Comment by filmote** [comment]
8 ![recording_20230425193733](https://user-images.githubusercontent.com/17228490/234221923-07f78887-54b8-4428-ac5b-d8100d286420.gif)
7 ![recording_20230425193713](https://user-images.githubusercontent.com/17228490/234221942-9e3dbfec-cf1d-4cdf-8d2e-01cbd484b243.gif)
6 ![recording_20230425193623](https://user-images.githubusercontent.com/17228490/234221948-b79f4386-e3ef-42fe-9c0a-985080187b2f.gif)

**Comment by filmote** [comment]
2 ![recording_20230425193507](https://user-images.githubusercontent.com/17228490/234222220-1a6f0ccd-3c09-43cf-a9b8-1e0826250276.gif)
1 ![recording_20230425193444](https://user-images.githubusercontent.com/17228490/234222229-922bd469-9438-4546-b2b8-76a428254fcc.gif)
0 ![recording_20230425193432](https://user-images.githubusercontent.com/17228490/234222236-6c35d24d-f19b-4df5-94c9-d49506097ca4.gif)

**Comment by filmote** [comment]
11 ![recording_20230425193308](https://user-images.githubusercontent.com/17228490/234222343-a3516387-e0ed-4f14-82b9-193059be518a.gif)
10 ![recording_20230425193256](https://user-images.githubusercontent.com/17228490/234222353-5ddd45d4-8fc9-4fac-a07f-37ba4672e44a.gif)
9 ![recording_20230425193210](https://user-images.githubusercontent.com/17228490/234222365-788e48fe-e82c-4a88-bd93-d93ddc782221.gif)

**Comment by filmote** [comment]
I cannot re-produce it.

Can you comment out `#define PRODUCTION_SETTINGS` and record it?

**Comment by MrBlinky** [comment]
After climbing up the platform:
*  I run/walk into the wall and then release all buttons after the prince stops moving
*  I press (and hold) left and immediately thereafter press jump
*   while jumping is still in progress I release the buttons and press and hold right continiously until I walked through the wall

![recording_20230425125357](https://user-images.githubusercontent.com/4971163/234243279-1ca309a2-da4d-4126-8b13-ac2bd82ff241.gif)

**Comment by filmote** [comment]
OK, I will try again!

**Comment by MrBlinky** [comment]
cannot recreate it in the new beta 19. You've fixed it!
