### ISSUE TITLE
Effortless walk through the wall.

### ISSUE THREAD

**Issue by MrBlinky** [Press-Play-On-Tape/PrinceOfArabia#165]
beta19 introduced a new through the wall issue.
On the start room, just walk continiously right and you walk through the wall.
When the game starts press and hold down right until you've walked through the wall.

![recording_20230427124326](https://user-images.githubusercontent.com/4971163/234826036-bfac8079-ad3a-4264-b421-73fc220b5048.gif)

**Comment by MrBlinky** [comment]
With debug data:

![recording_20230427140733](https://user-images.githubusercontent.com/4971163/234844664-e0c08f7f-6514-496e-805d-1f15b5de71ef.gif)

**Comment by MrBlinky** [comment]
Here's some more info L1 exit room,
when start running to the right from px = 2 you bump into the wall normally
when start running to the right from px = 6 (after a single crouch right) you fall through the wall

![recording_20230427233125](https://user-images.githubusercontent.com/4971163/234984541-f7c1841a-c6fc-4dbf-b6dc-d497d0486d53.gif)

same for px=86 amd px = 90

![recording_20230427233734](https://user-images.githubusercontent.com/4971163/234985415-b1851930-6292-490f-b805-366442d7840b.gif)

going 94 and up works fine

![recording_20230427234018](https://user-images.githubusercontent.com/4971163/234985883-52ca9b6f-5387-4e99-acc9-2c7117ec3c99.gif)

looks like whenever you start running where px % 12 == 6 you'll fall through the wall

**Comment by filmote** [comment]
Version 1.01 Beta 020

**Comment by MrBlinky** [comment]
can't reproduce with beta20, fixed
