### ISSUE TITLE
jump left / fall down into wall offset (skywalker) issue

### ISSUE THREAD

**Issue by MrBlinky** [Press-Play-On-Tape/PrinceOfArabia#166]
beta 19: level 1 start room: climbing up and jumping left will cause the prince to land a pixel higher. Repeat this many times and you end up skywalking.

To reproduce. climb up the platform, turn left,release buttons and then press the jump.

![recording_20230427131534](https://user-images.githubusercontent.com/4971163/234834048-ae145139-cade-4097-b79c-2d7848210a3c.gif)

**Comment by filmote** [comment]
Version 1.01 Beta 020
