### ISSUE TITLE
far jump landing through the wall

### ISSUE THREAD

**Issue by MrBlinky** [Press-Play-On-Tape/PrinceOfArabia#167]
beta 19 Level 1 startroom: clim up and walk into the wall then turn around and run left. If you time it right you can make two (semi) long jumps. When you'll land you'll drop through the wall.

![recording_20230427135106](https://user-images.githubusercontent.com/4971163/234842164-ae02108f-d365-458b-a669-7190a3fb9504.gif)

![recording_20230427135023](https://user-images.githubusercontent.com/4971163/234841867-45084ff7-1b32-4432-b18c-aa76fc53db73.gif)

**Comment by filmote** [comment]
Version 1.01 Beta 020
