### ISSUE TITLE
L1 jump with fall issue

### ISSUE THREAD

**Issue by MrBlinky** [Press-Play-On-Tape/PrinceOfArabia#172]
beta 22, jumping and falling here ends inside the wall. When moving left or right will make you fall off the map.

![recording_20230502010838](https://user-images.githubusercontent.com/4971163/235540403-2ce69192-55b3-4927-8902-4762afd98259.gif)

**Comment by MrBlinky** [comment]
can also be recreated L2 start room.

![recording_20230502012451](https://user-images.githubusercontent.com/4971163/235542149-dc5a8194-ead2-4be2-a9a4-33cc4f0f0474.gif)

key is jumping and falling when px %12 == 2 lands you inside a wall

**Comment by filmote** [comment]
Fixed in Beta 23 (maybe :( )

**Comment by MrBlinky** [comment]
Can not reproduce this anymore

**Comment by MrBlinky** [comment]
Looks like I was too quick closing this issue.
Reopend it as  I'm able to reproduce it when px == 30 

![recording_20230502185848](https://user-images.githubusercontent.com/4971163/235721528-664b929f-a34b-4387-a4fb-82fa86dae18c.gif)

**Comment by filmote** [comment]
Nice.  Think I got it!

Beta 24?




![Image](https://user-images.githubusercontent.com/17228490/235865401-657b8483-7945-4e39-81c6-da7a57115bc1.gif)

**Comment by MrBlinky** [comment]
Yep you got it in released beta 23. I cannot recreate it from any px value now.
