### ISSUE TITLE
L1 short jump fail

### ISSUE THREAD

**Issue by MrBlinky** [Press-Play-On-Tape/PrinceOfArabia#173]
beta22 in L1 when standing at position px = 102. jumping to the left by just pressing jump will fail and land you on a tile lower.

![recording_20230502012005](https://user-images.githubusercontent.com/4971163/235541563-794ceb7f-7408-4f46-8778-b68051a73c67.gif)

**Comment by MrBlinky** [comment]
same here on L2 when px = 42

![recording_20230502013336](https://user-images.githubusercontent.com/4971163/235543242-2d17b78b-ce8b-4746-92f7-e41b3d31c12c.gif)

so it fails when px % 12 == 6

**Comment by filmote** [comment]
Fixed in Beta 23 (maybe :( )

**Comment by MrBlinky** [comment]
Just rebuild from latest source and it's still there.

**Comment by filmote** [comment]
Beta 24.
