### ISSUE TITLE
L9 jump through wall

### ISSUE THREAD

**Issue by MrBlinky** [Press-Play-On-Tape/PrinceOfArabia#177]
On L9 It's possible to jump through wall when running left.

![recording_20230506012900](https://user-images.githubusercontent.com/4971163/236578947-4dbbca50-657d-4a87-899d-c0d0ae56f067.gif)

**Comment by filmote** [comment]
Update in repo.

**Comment by MrBlinky** [comment]
confirmed fixed in beta 25
