### ISSUE TITLE
L10 enemy positioning

### ISSUE THREAD

**Issue by MrBlinky** [Press-Play-On-Tape/PrinceOfArabia#178]
in L10 you can ommit a part of the level by controlling the position of the enemy:
going  to the room at the right and returning to the room left will position the enemy on the left.

![recording_20230506014756](https://user-images.githubusercontent.com/4971163/236581728-c7e8bb12-e4a9-4e0b-84f6-03e96a5f5cc5.gif)

**Comment by filmote** [comment]
I have made the enemy more to the right when you leave and come back into the room.  You can still climb up and try to attack him .. sometimes you can get your weapon out quick enough, other times he just kills you.

**Comment by MrBlinky** [comment]
beta25, Yes managed to kill him on the 1st attempt. How much further can the enemy be positioned to the right?

**Comment by filmote** [comment]
I moved him another 8px to the right.  It is still possible to get your sword out .. but less so.

**Comment by MrBlinky** [comment]
Yeah it's much tougher now. your odds to win are very low now.
