### ISSUE TITLE
Hidden floor button

### ISSUE THREAD

**Issue by ace-dent** [Press-Play-On-Tape/PrinceOfArabia#92]
Tested with v1.0024, FX Hardware.
L4 - One of the gate buttons seems hidden under a normal platform tile. Is that by design?
If not, is there a way to scan all level data for such overlaps? (Programatically / scripted before compilation).

https://user-images.githubusercontent.com/473224/224020094-baf7d2ad-457f-41c3-8666-b55cce0edbe7.mov

**Comment by ace-dent** [comment]
Was retested. Can be closed.

**Comment by filmote** [comment]
Thanks, I will close.
